# Eureka Service Registry Configuration
# This is the service discovery server where all microservices register themselves

server:
  port: 8761  # Standard Eureka server port

spring:
  application:
    name: service-registry  # Service name

# Eureka Server Configuration
eureka:
  instance:
    hostname: localhost  # Server hostname
  client:
    register-with-eureka: false  # Don't register itself with Eureka
    fetch-registry: false        # Don't fetch registry from other Eureka servers
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # Self URL